name: docker-ci

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    name: 🐳 Docker build and push
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            arnyminerz/escalaralcoiaicomtat_backend:${{ steps.vars.outputs.tag }}
            arnyminerz/escalaralcoiaicomtat_backend:latest
          platforms: linux/arm64,linux/arm/v7,linux/amd64
